import type { csPlayer } from "../cs/player";

/** Generated by `node scripts/i18n.mjs import`. Missing keys fall back to Czech. */
export const enPlayer: Partial<Record<keyof typeof csPlayer, string>> = {
  "player.transport.play": "Play",
  "player.transport.pause": "Pause",
  "player.timeline.position": "{current} / {total}",
  "player.speed.rate": "{value}×",
};
