/** Translation dictionaries.
 *
 *  Generated by `npm run i18n:sync`. Add a screen with `npm run i18n:new`
 *  rather than editing this file; `npm run i18n:check` fails when it no
 *  longer matches the dictionaries on disk.
 *
 *  Czech is the source language and is always complete: `TranslationKey` is
 *  derived from it, so adding a key means adding it here first. Other languages
 *  are deliberately typed as partial, because translation happens in bulk and an
 *  English dictionary that had to be complete would either block that work or
 *  fill the interface with untranslated placeholders. `useI18n().t` falls back
 *  to Czech instead.
 *
 *  Keys are `namespace.area.name`. Plural forms add a CLDR category suffix
 *  (`.one`, `.few`, `.many`, `.other`) and are read through `tPlural`.
 *
 *  `*Context` maps carry translator notes for keys whose meaning is not obvious
 *  from the text alone — a bare `Model` or `Kontrola` is a coin flip without
 *  them. They are shipped to the translator by the export script and are not
 *  used at runtime.
 */
import { csApp, csAppContext } from "./cs/app";
import { csCatalog, csCatalogContext } from "./cs/catalog";
import { csCommon, csCommonContext } from "./cs/common";
import { csDetail, csDetailContext } from "./cs/detail";
import { csDialogs, csDialogsContext } from "./cs/dialogs";
import { csDomain, csDomainContext } from "./cs/domain";
import { csErrors, csErrorsContext } from "./cs/errors";
import { csLibrary, csLibraryContext } from "./cs/library";
import { csPlayer, csPlayerContext } from "./cs/player";
import { csProgress, csProgressContext } from "./cs/progress";
import { csSave, csSaveContext } from "./cs/save";
import { csSettings, csSettingsContext } from "./cs/settings";
import { csWizard, csWizardContext } from "./cs/wizard";

import { enApp } from "./en/app";
import { enCatalog } from "./en/catalog";
import { enCommon } from "./en/common";
import { enDetail } from "./en/detail";
import { enDialogs } from "./en/dialogs";
import { enDomain } from "./en/domain";
import { enErrors } from "./en/errors";
import { enLibrary } from "./en/library";
import { enPlayer } from "./en/player";
import { enProgress } from "./en/progress";
import { enSave } from "./en/save";
import { enSettings } from "./en/settings";
import { enWizard } from "./en/wizard";

export const cs = {
  ...csApp,
  ...csCatalog,
  ...csCommon,
  ...csDetail,
  ...csDialogs,
  ...csDomain,
  ...csErrors,
  ...csLibrary,
  ...csPlayer,
  ...csProgress,
  ...csSave,
  ...csSettings,
  ...csWizard,
};

export type TranslationKey = keyof typeof cs;

export const en: Partial<Record<TranslationKey, string>> = {
  ...enApp,
  ...enCatalog,
  ...enCommon,
  ...enDetail,
  ...enDialogs,
  ...enDomain,
  ...enErrors,
  ...enLibrary,
  ...enPlayer,
  ...enProgress,
  ...enSave,
  ...enSettings,
  ...enWizard,
};

/** Translator notes, keyed exactly like the dictionaries. Build tooling only. */
export const csContext: Partial<Record<TranslationKey, string>> = {
  ...csAppContext,
  ...csCatalogContext,
  ...csCommonContext,
  ...csDetailContext,
  ...csDialogsContext,
  ...csDomainContext,
  ...csErrorsContext,
  ...csLibraryContext,
  ...csPlayerContext,
  ...csProgressContext,
  ...csSaveContext,
  ...csSettingsContext,
  ...csWizardContext,
};

export const NAMESPACES = [
  "app",
  "catalog",
  "common",
  "detail",
  "dialogs",
  "domain",
  "errors",
  "library",
  "player",
  "progress",
  "save",
  "settings",
  "wizard",
] as const;

export type Namespace = (typeof NAMESPACES)[number];
